// Application configuration
// =========================
// Defines config options for common,
// development, and test environment.
//
// In production you should use the
// ecosystem.json file generated by PM2.

'use strict';

let session     = require('express-session'),
    RedisStore  = require('connect-redis')(session);

module.exports = {
  common: {
    handlebars: {
      defaultLayout:  'default',
      helpers:        require('../lib/helpers'),
      extname:        '.hbs',
      layoutsDir:     __dirname + '/../views/layouts',
      partialsDir:    __dirname + '/../views/partials'
    },
    sessions: {
      secret:             process.env.SESSION_SECRET,
      name:               'coverage.sid',
      resave:             false,
      saveUninitialized:  false,
      unset:              'destroy'
    }
  },
  development: {
    PORT: 9000,
    sessions: {
      cookie: { secure: false }
    }
  },
  test: {},
  production: {
    sessions: {
      store: new RedisStore({
        host: process.env.REDIS_HOST,
        port: process.env.REDIS_PORT,        
        ttl:  7200000 // 2 hours
      }),
      cookie: { secure: true }
    }
  }
};
