// Application configuration
// =========================
// Defines config options for common,
// development, and test environment.
//
// In production you should use the
// ecosystem.json file generated by PM2.

'use strict';

module.exports = {
  common: {
    handlebars: {
      defaultLayout:  'default',
      helpers:        require('../lib/helpers'),
      extname:        '.hbs',
      layoutsDir:     __dirname + '/../views/layouts',
      partialsDir:    __dirname + '/../views/partials'
    }
  },
  development: {
    PORT: 9000
  },
  test: {},
  production: {
    // Do not fill this in.
    // Use PM2 to set your environment
    // variables instead. This object is left
    // here just to call this to your attention.
  }
};
